 # missing data 
# tempolayal data 
# catefgorical varables : remove rare lable 
# stable the values of the varables of the same range

In [1]:
df = pd.read_csv('train.csv')
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [2]:
#miising of catogrical fea

feature_nan_cat =[feature for feature in df.columns if df[feature].isnull().sum()>1 and df[feature].dtypes=='O']
for feature in feature_nan_cat:
    print('{}: {}% missing values'.format(feature,np.round(df[feature].isnull().mean(),4)))

Alley: 0.9377% missing values

MasVnrType: 0.0055% missing values

BsmtQual: 0.0253% missing values

BsmtCond: 0.0253% missing values

BsmtExposure: 0.026% missing values

BsmtFinType1: 0.0253% missing values

BsmtFinType2: 0.026% missing values

FireplaceQu: 0.4726% missing values

GarageType: 0.0555% missing values

GarageFinish: 0.0555% missing values

GarageQual: 0.0555% missing values

GarageCond: 0.0555% missing values

PoolQC: 0.9952% missing values

Fence: 0.8075% missing values

MiscFeature: 0.963% missing values

In [3]:
 #replacing missing features 
def replace_cat_fer(df,feature_nan_cat):
    data=df.copy()
    data[feature_nan_cat]=df[feature_nan_cat].fillna('missing')
    return data
df= replace_cat_fer(df,feature_nan_cat)

In [4]:
df[feature_nan_cat].isnull().sum()

Alley           0
MasVnrType      0
BsmtQual        0
BsmtCond        0
BsmtExposure    0
BsmtFinType1    0
BsmtFinType2    0
FireplaceQu     0
GarageType      0
GarageFinish    0
GarageQual      0
GarageCond      0
PoolQC          0
Fence           0
MiscFeature     0
dtype: int64

In [5]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,missing,Reg,Lvl,AllPub,...,0,missing,missing,missing,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,missing,Reg,Lvl,AllPub,...,0,missing,missing,missing,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,missing,IR1,Lvl,AllPub,...,0,missing,missing,missing,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,missing,IR1,Lvl,AllPub,...,0,missing,missing,missing,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,missing,IR1,Lvl,AllPub,...,0,missing,missing,missing,0,12,2008,WD,Normal,250000

In [6]:
#numical feture
feature_nan_num =[feature for feature in df.columns if df[feature].isnull().sum()>1 and df[feature].dtypes!='O']
for feature in feature_nan_num:
    print('{}: {}% missing values'.format(feature,np.round(df[feature].isnull().mean(),4)))

LotFrontage: 0.1774% missing values

MasVnrArea: 0.0055% missing values

GarageYrBlt: 0.0555% missing values

In [7]:
#numacal missing valu handel
for feature in feature_nan_num:
    median_val=df[feature].median()
    
    df[feature +'fea'] = np.where(df[feature].isnull(),1,0)
    df[feature].fillna(median_val,inplace=True)

In [8]:
df.head(50)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagefea,MasVnrAreafea,GarageYrBltfea
0,1,60,RL,65.0,8450,Pave,missing,Reg,Lvl,AllPub,...,missing,0,2,2008,WD,Normal,208500,0,0,0
1,2,20,RL,80.0,9600,Pave,missing,Reg,Lvl,AllPub,...,missing,0,5,2007,WD,Normal,181500,0,0,0
2,3,60,RL,68.0,11250,Pave,missing,IR1,Lvl,AllPub,...,missing,0,9,2008,WD,Normal,223500,0,0,0
3,4,70,RL,60.0,9550,Pave,missing,IR1,Lvl,AllPub,...,missing,0,2,2006,WD,Abnorml,140000,0,0,0
4,5,60,RL,84.0,14260,Pave,missing,IR1,Lvl,AllPub,...,missing,0,12,2008,WD,Normal,250000,0,0,0
5,6,50,RL,85.0,14115,Pave,missing,IR1,Lvl,AllPub,...,Shed,700,10,2009,WD,Normal,143000,0,0,0
6,7,20,RL,75.0,10084,Pave,missing,Reg,Lvl,AllPub,...,missing,0,8,2007,WD,Normal,307000,0,0,0
7,8,60,RL,69.0,10382,Pave,missing,IR1,Lvl,AllPub,...,Shed,350,11,2009,WD,Normal,200000,1,0,0
8,9,50,RM,51.0,6120,Pave,missing,Reg,Lvl,AllPub,...,missing,0,4,2008,WD,Abnorml,129900,0,0,0
9,10,190,RL,50.0,7420,Pave,missing,Reg,Lvl,AllPub,...,missing,0,1,2008,WD,Normal,118000,0,0,0
10,11,20,RL,70.0,11200,Pave,missing,Reg,Lvl,AllPub,...,missing,0,2,2008,WD,Normal,129500,0,0,0
11,12,60,RL,85.0,11924,Pave,missing,IR1,Lvl,AllPub,...,missing,0,7,2006,New,Partial,345000,0,0,0
12,13,20,RL,69.0,12968,Pave,missing,IR2,Lvl,AllPub,...,missing,0,9,2008,WD,Normal,144000,1,0,0
13,14,20,RL,91.0,10652,Pave,missing,IR1,Lvl,AllPub,...,missing,0,8,2007,New,Partial,279500,0,0,0
14,15,20,RL,69.0,10920,Pave,missing,IR1,Lvl,AllPub,...,missing,0,5,2008,WD,Normal,157000,1,0,0
15,16,45,RM,51.0,6120,Pave,missing,Reg,Lvl,AllPub,...,missing,0,7,2007,WD,Normal,132000,0,0,0
16,17,20,RL,69.0,11241,Pave,missing,IR1,Lvl,AllPub,...,Shed,700,3,2010,WD,Normal,149000,1,0,0
17,18,90,RL,72.0,10791,Pave,missing,Reg,Lvl,AllPub,...,Shed,500,10,2006,WD,Normal,90000,0,0,0
18,19,20,RL,66.0,13695,Pave,missing,Reg,Lvl,AllPub,...,missing,0,6,2008,WD,Normal,159000,0,0,0
19,20,20,RL,70.0,7560,Pave,missing,Reg,Lvl,AllPub,...,missing,0,5,2009,COD,Abnorml,139000,0,0,0
20,21,60,RL,101.0,14215,Pave,missing,IR1,Lvl,AllPub,...,missing,0,11,2006,New,Partial,325300,0,0,0
21,22,45,RM,57.0,7449,Pave,Grvl,Reg,Bnk,AllPub,...,missing,0,6,2007,WD,Normal,139400,0,0,0
22,23,20,RL,75.0,9742,Pave,missing,Reg,Lvl,AllPub,...,missing,0,9,2008,WD,Normal,230000,0,0,0
23,24,120,RM,44.0,4224,Pave,missing,Reg,Lvl,AllPub,...,missing,0,6,2007,WD,Normal,129900,0,0,0
24,25,20,RL,69.0,8246,Pave,missing,IR1,Lvl,AllPub,...,missing,0,5,2010,WD,Normal,154000,1,0,0
25,26,20,RL,110.0,14230,Pave,missing,Reg,Lvl,AllPub,...,missing,0,7,2009,WD,Normal,256300,0,0,0
26,27,20,RL,60.0,7200,Pave,missing,Reg,Lvl,AllPub,...,missing,0,5,2010,WD,Normal,134800,0,0,0
27,28,20,RL,98.0,11478,Pave,missing,Reg,Lvl,AllPub,...,missing,0,5,2010,WD,Normal,306000,0,0,0
28,29,20,RL,47.0,16321,Pave,missing,IR1,Lvl,AllPub,...,missing,0,12,2006,WD,Normal,207500,0,0,0
29,30,30,RM,60.0,6324,Pave,missing,IR1,Lvl,AllPub,...,missing,0,5,2008,WD,Normal,68500,0,0,0
30,31,70,C (all),50.0,8500,Pave,Pave,Reg,Lvl,AllPub,...,missing,0,7,2008,WD,Normal,40000,0,0,0
31,32,20,RL,69.0,8544,Pave,missing,IR1,Lvl,AllPub,...,missing,0,6,2008,WD,Normal,149350,1,0,0
32,33,20,RL,85.0,11049,Pave,missing,Reg,Lvl,AllPub,...,missing,0,1,2008,WD,Normal,179900,0,0,0
33,34,20,RL,70.0,10552,Pave,missing,IR1,Lvl,AllPub,...,missing,0,4,2010,WD,Normal,165500,0,0,0
34,35,120,RL,60.0,7313,Pave,missing,Reg,Lvl,AllPub,...,missing,0,8,2007,WD,Normal,277500,0,0,0
35,36,60,RL,108.0,13418,Pave,missing,Reg,Lvl,AllPub,...,missing,0,9,2006,WD,Normal,309000,0,0,0
36,37,20,RL,112.0,10859,Pave,missing,Reg,Lvl,AllPub,...,missing,0,6,2009,WD,Normal,145000,0,0,0
37,38,20,RL,74.0,8532,Pave,missing,Reg,Lvl,AllPub,...,missing,0,10,2009,WD,Normal,153000,0,0,0
38,39,20,RL,68.0,7922,Pave,missing,Reg,Lvl,AllPub,...,missing,0,1,2010,WD,Abnorml,109000,0,0,0
39,40,90,RL,65.0,6040,Pave,missing,Reg,Lvl,AllPub,...,missing,0,6,2008,WD,AdjLand,82000,0,0,1
40,41,20,RL,84.0,8658,Pave,missing,Reg,Lvl,AllPub,...,missing,0,12,2006,WD,Abnorml,160000,0,0,0
41,42,20,RL,115.0,16905,Pave,missing,Reg,Lvl,AllPub,...,missing,0,7,2007,WD,Normal,170000,0,0,0
42,43,85,RL,69.0,9180,Pave,missing,IR1,Lvl,AllPub,...,missing,0,12,2007,WD,Normal,144000,1,0,0
43,44,20,RL,69.0,9200,Pave,missing,IR1,Lvl,AllPub,...,missing,0,7,2008,WD,Normal,130250,1,0,0
44,45,20,RL,70.0,7945,Pave,missing,Reg,Lvl,AllPub,...,missing,0,5,2006,WD,Normal,141000,0,0,0
45,46,120,RL,61.0,7658,Pave,missing,Reg,Lvl,AllPub,...,missing,0,2,2010,WD,Normal,319900,0,0,0
46,47,50,RL,48.0,12822,Pave,missing,IR1,Lvl,AllPub,...,missing,0,8,2009,WD,Abnorml,239686,0,0,0
47,48,20,FV,84.0,11096,Pave,missing,Reg,Lvl,AllPub,...,missing,0,7,2007,WD,Normal,249700,0,0,0
48,49,190,RM,33.0,4456,Pave,missing,Reg,Lvl,AllPub,...,missing,0,6,2009,New,Partial,113000,0,0,1
49,50,20,RL,66.0,7742,Pave,missing,Reg,Lvl,AllPub,...,missing,0,1,2007,WD,Normal,127000,0,0,0

In [9]:
## Temporal Variables (Date Time Variables)

for feature in ['YearBuilt','YearRemodAdd','GarageYrBlt']:
       
    df[feature]=df['YrSold']-df[feature]

In [10]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagefea,MasVnrAreafea,GarageYrBltfea
0,1,60,RL,65.0,8450,Pave,missing,Reg,Lvl,AllPub,...,missing,0,2,2008,WD,Normal,208500,0,0,0
1,2,20,RL,80.0,9600,Pave,missing,Reg,Lvl,AllPub,...,missing,0,5,2007,WD,Normal,181500,0,0,0
2,3,60,RL,68.0,11250,Pave,missing,IR1,Lvl,AllPub,...,missing,0,9,2008,WD,Normal,223500,0,0,0
3,4,70,RL,60.0,9550,Pave,missing,IR1,Lvl,AllPub,...,missing,0,2,2006,WD,Abnorml,140000,0,0,0
4,5,60,RL,84.0,14260,Pave,missing,IR1,Lvl,AllPub,...,missing,0,12,2008,WD,Normal,250000,0,0,0

In [11]:
import numpy as np
num_features=['LotFrontage', 'LotArea', '1stFlrSF', 'GrLivArea', 'SalePrice']

for feature in num_features:
    df[feature]=np.log(df[feature])

In [12]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagefea,MasVnrAreafea,GarageYrBltfea
0,1,60,RL,4.174387,9.041922,Pave,missing,Reg,Lvl,AllPub,...,missing,0,2,2008,WD,Normal,12.247694,0,0,0
1,2,20,RL,4.382027,9.169518,Pave,missing,Reg,Lvl,AllPub,...,missing,0,5,2007,WD,Normal,12.109011,0,0,0
2,3,60,RL,4.219508,9.328123,Pave,missing,IR1,Lvl,AllPub,...,missing,0,9,2008,WD,Normal,12.317167,0,0,0
3,4,70,RL,4.094345,9.164296,Pave,missing,IR1,Lvl,AllPub,...,missing,0,2,2006,WD,Abnorml,11.849398,0,0,0
4,5,60,RL,4.430817,9.565214,Pave,missing,IR1,Lvl,AllPub,...,missing,0,12,2008,WD,Normal,12.429216,0,0,0

# Handling Rare Categorical Feature

In [13]:
categorical_features=[feature for feature in df.columns if df[feature].dtype=='O']

In [14]:
categorical_features

['MSZoning',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition']

In [15]:
for feature in categorical_features:
    temp=df.groupby(feature)['SalePrice'].count()/len(df)
    temp_df=temp[temp>0.01].index
    df[feature]=np.where(df[feature].isin(temp_df),df[feature],'Rare_var')

In [16]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagefea,MasVnrAreafea,GarageYrBltfea
0,1,60,RL,4.174387,9.041922,Pave,missing,Reg,Lvl,AllPub,...,missing,0,2,2008,WD,Normal,12.247694,0,0,0
1,2,20,RL,4.382027,9.169518,Pave,missing,Reg,Lvl,AllPub,...,missing,0,5,2007,WD,Normal,12.109011,0,0,0
2,3,60,RL,4.219508,9.328123,Pave,missing,IR1,Lvl,AllPub,...,missing,0,9,2008,WD,Normal,12.317167,0,0,0
3,4,70,RL,4.094345,9.164296,Pave,missing,IR1,Lvl,AllPub,...,missing,0,2,2006,WD,Abnorml,11.849398,0,0,0
4,5,60,RL,4.430817,9.565214,Pave,missing,IR1,Lvl,AllPub,...,missing,0,12,2008,WD,Normal,12.429216,0,0,0

In [17]:
for feature in categorical_features:
    labels_ordered=df.groupby([feature])['SalePrice'].mean().sort_values().index
    labels_ordered={k:i for i,k in enumerate(labels_ordered,0)}
    df[feature]=df[feature].map(labels_ordered)

In [18]:
df.head(50)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagefea,MasVnrAreafea,GarageYrBltfea
0,1,60,3,4.174387,9.041922,1,2,0,1,1,...,2,0,2,2008,2,3,12.247694,0,0,0
1,2,20,3,4.382027,9.169518,1,2,0,1,1,...,2,0,5,2007,2,3,12.109011,0,0,0
2,3,60,3,4.219508,9.328123,1,2,1,1,1,...,2,0,9,2008,2,3,12.317167,0,0,0
3,4,70,3,4.094345,9.164296,1,2,1,1,1,...,2,0,2,2006,2,0,11.849398,0,0,0
4,5,60,3,4.430817,9.565214,1,2,1,1,1,...,2,0,12,2008,2,3,12.429216,0,0,0
5,6,50,3,4.442651,9.554993,1,2,1,1,1,...,1,700,10,2009,2,3,11.870600,0,0,0
6,7,20,3,4.317488,9.218705,1,2,0,1,1,...,2,0,8,2007,2,3,12.634603,0,0,0
7,8,60,3,4.234107,9.247829,1,2,1,1,1,...,1,350,11,2009,2,3,12.206073,1,0,0
8,9,50,1,3.931826,8.719317,1,2,0,1,1,...,2,0,4,2008,2,0,11.774520,0,0,0
9,10,190,3,3.912023,8.911934,1,2,0,1,1,...,2,0,1,2008,2,3,11.678440,0,0,0
10,11,20,3,4.248495,9.323669,1,2,0,1,1,...,2,0,2,2008,2,3,11.771436,0,0,0
11,12,60,3,4.442651,9.386308,1,2,1,1,1,...,2,0,7,2006,3,4,12.751300,0,0,0
12,13,20,3,4.234107,9.470240,1,2,3,1,1,...,2,0,9,2008,2,3,11.877569,1,0,0
13,14,20,3,4.510860,9.273503,1,2,1,1,1,...,2,0,8,2007,3,4,12.540758,0,0,0
14,15,20,3,4.234107,9.298351,1,2,1,1,1,...,2,0,5,2008,2,3,11.964001,1,0,0
15,16,45,1,3.931826,8.719317,1,2,0,1,1,...,2,0,7,2007,2,3,11.790557,0,0,0
16,17,20,3,4.234107,9.327323,1,2,1,1,1,...,1,700,3,2010,2,3,11.911702,1,0,0
17,18,90,3,4.276666,9.286468,1,2,0,1,1,...,1,500,10,2006,2,3,11.407565,0,0,0
18,19,20,3,4.189655,9.524786,1,2,0,1,1,...,2,0,6,2008,2,3,11.976659,0,0,0
19,20,20,3,4.248495,8.930626,1,2,0,1,1,...,2,0,5,2009,0,0,11.842229,0,0,0
20,21,60,3,4.615121,9.562053,1,2,1,1,1,...,2,0,11,2006,3,4,12.692503,0,0,0
21,22,45,1,4.043051,8.915835,1,0,0,0,1,...,2,0,6,2007,2,3,11.845103,0,0,0
22,23,20,3,4.317488,9.184202,1,2,0,1,1,...,2,0,9,2008,2,3,12.345835,0,0,0
23,24,120,1,3.784190,8.348538,1,2,0,1,1,...,2,0,6,2007,2,3,11.774520,0,0,0
24,25,20,3,4.234107,9.017484,1,2,1,1,1,...,2,0,5,2010,2,3,11.944708,1,0,0
25,26,20,3,4.700480,9.563108,1,2,0,1,1,...,2,0,7,2009,2,3,12.454104,0,0,0
26,27,20,3,4.094345,8.881836,1,2,0,1,1,...,2,0,5,2010,2,3,11.811547,0,0,0
27,28,20,3,4.584967,9.348187,1,2,0,1,1,...,2,0,5,2010,2,3,12.631340,0,0,0
28,29,20,3,3.850148,9.700208,1,2,1,1,1,...,2,0,12,2006,2,3,12.242887,0,0,0
29,30,30,1,4.094345,8.752107,1,2,1,1,1,...,2,0,5,2008,2,3,11.134589,0,0,0
30,31,70,0,3.912023,9.047821,1,1,0,1,1,...,2,0,7,2008,2,3,10.596635,0,0,0
31,32,20,3,4.234107,9.052985,1,2,1,1,1,...,2,0,6,2008,2,3,11.914048,1,0,0
32,33,20,3,4.442651,9.310095,1,2,0,1,1,...,2,0,1,2008,2,3,12.100156,0,0,0
33,34,20,3,4.248495,9.264071,1,2,1,1,1,...,2,0,4,2010,2,3,12.016726,0,0,0
34,35,120,3,4.094345,8.897409,1,2,0,1,1,...,2,0,8,2007,2,3,12.533576,0,0,0
35,36,60,3,4.682131,9.504352,1,2,0,1,1,...,2,0,9,2006,2,3,12.641097,0,0,0
36,37,20,3,4.718499,9.292750,1,2,0,1,1,...,2,0,6,2009,2,3,11.884489,0,0,0
37,38,20,3,4.304065,9.051579,1,2,0,1,1,...,2,0,10,2009,2,3,11.938193,0,0,0
38,39,20,3,4.219508,8.977399,1,2,0,1,1,...,2,0,1,2010,2,0,11.599103,0,0,0
39,40,90,3,4.174387,8.706159,1,2,0,1,1,...,2,0,6,2008,2,1,11.314475,0,0,1
40,41,20,3,4.430817,9.066239,1,2,0,1,1,...,2,0,12,2006,2,0,11.982929,0,0,0
41,42,20,3,4.744932,9.735365,1,2,0,1,1,...,2,0,7,2007,2,3,12.043554,0,0,0
42,43,85,3,4.234107,9.124782,1,2,1,1,1,...,2,0,12,2007,2,3,11.877569,1,0,0
43,44,20,3,4.234107,9.126959,1,2,1,1,1,...,2,0,7,2008,2,3,11.777211,1,0,0
44,45,20,3,4.248495,8.980298,1,2,0,1,1,...,2,0,5,2006,2,3,11.856515,0,0,0
45,46,120,3,4.110874,8.943506,1,2,0,1,1,...,2,0,2,2010,2,3,12.675764,0,0,0
46,47,50,3,3.871201,9.458918,1,2,1,1,1,...,2,0,8,2009,2,0,12.387085,0,0,0
47,48,20,4,4.430817,9.314340,1,2,0,1,1,...,2,0,7,2007,2,3,12.428015,0,0,0
48,49,190,1,3.496508,8.402007,1,2,0,1,1,...,2,0,6,2009,3,4,11.635143,0,0,1
49,50,20,3,4.189655,8.954415,1,2,0,1,1,...,2,0,1,2007,2,3,11.751942,0,0,0

# feacture scaling

In [19]:
feacuture_scale =[feature for feature in df.columns if feature not in ['Id','SalePrice']  ]

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(df[feacuture_scale])

MinMaxScaler()

In [23]:
scaler.transform(df[feacuture_scale])

array([[0.23529412, 0.75      , 0.41820812, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.75      , 0.49506375, ..., 0.        , 0.        ,
        0.        ],
       [0.23529412, 0.75      , 0.434909  , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.29411765, 0.75      , 0.42385922, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.75      , 0.434909  , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.75      , 0.47117546, ..., 0.        , 0.        ,
        0.        ]])

In [28]:
data = pd.concat([df[['Id', 'SalePrice']].reset_index(drop=True),
                    pd.DataFrame(scaler.transform(df[feacuture_scale]), columns=feacuture_scale)],
                    axis=1)

In [29]:
data.head()

,Id,SalePrice,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,LotFrontagefea,MasVnrAreafea,GarageYrBltfea
0,1,12.247694,0.235294,0.75,0.418208,0.366344,1.0,1.0,0.000000,0.333333,...,1.0,1.0,0.0,0.090909,0.50,0.666667,0.75,0.0,0.0,0.0
1,2,12.109011,0.000000,0.75,0.495064,0.391317,1.0,1.0,0.000000,0.333333,...,1.0,1.0,0.0,0.363636,0.25,0.666667,0.75,0.0,0.0,0.0
2,3,12.317167,0.235294,0.75,0.434909,0.422359,1.0,1.0,0.333333,0.333333,...,1.0,1.0,0.0,0.727273,0.50,0.666667,0.75,0.0,0.0,0.0
3,4,11.849398,0.294118,0.75,0.388581,0.390295,1.0,1.0,0.333333,0.333333,...,1.0,1.0,0.0,0.090909,0.00,0.666667,0.00,0.0,0.0,0.0
4,5,12.429216,0.235294,0.75,0.513123,0.468761,1.0,1.0,0.333333,0.333333,...,1.0,1.0,0.0,1.000000,0.50,0.666667,0.75,0.0,0.0,0.0

In [31]:
data.to_csv('x_train.csv',index=False)